# Generated by Django 2.1.5 on 2019-05-02 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0046_auto_20190502_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patentss_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=600)),
                ('holder', models.CharField(max_length=600)),
                ('datesubmitprovisional', models.DateField()),
                ('datesubmitcomplete', models.DateField()),
                ('datepublication', models.DateField()),
                ('remarks', models.CharField(max_length=800)),
                ('emailid', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='patents_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='Patents_Details',
        ),
    ]
