# Generated by Django 2.1.5 on 2019-05-02 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0048_auto_20190502_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantss_Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('projectname', models.CharField(max_length=600)),
                ('agency', models.CharField(max_length=600)),
                ('grantamount', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=900)),
                ('emailid', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='grants_applied',
            name='user',
        ),
        migrations.DeleteModel(
            name='Grants_Applied',
        ),
    ]
