# Generated by Django 2.1.5 on 2019-05-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0054_auto_20190502_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('code', models.CharField(max_length=500)),
                ('credit', models.IntegerField()),
                ('created', models.DateField()),
                ('department', models.CharField(max_length=600)),
                ('semester', models.IntegerField()),
                ('coursedescription', models.CharField(max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='courses_detailss',
            name='user',
        ),
        migrations.DeleteModel(
            name='Courses_Detailss',
        ),
    ]
