# Generated by Django 2.1.5 on 2019-05-06 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0055_auto_20190506_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register44',
            new_name='hodregister',
        ),
    ]
