# Generated by Django 2.1.5 on 2019-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0056_auto_20190506_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('estd', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='departments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
