# Generated by Django 2.1.5 on 2019-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0058_auto_20190605_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='department',
            field=models.CharField(max_length=700),
        ),
    ]
