# Generated by Django 2.1.5 on 2019-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('estd', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
